// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '12345abcdef-12345abcdef',
    appId: '1:12345abcdef:web:12345abcdef',
    messagingSenderId: '12345abcdef',
    projectId: 'todo-app-12345abcdef',
    authDomain: 'todo-app-12345abcdef.firebaseapp.com',
    storageBucket: 'todo-app-12345abcdef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '12345abcdef-12345abcdef',
    appId: '1:12345abcdef:android:12345abcdef',
    messagingSenderId: '12345abcdef',
    projectId: 'todo-app-12345abcdef',
    storageBucket: 'todo-app-12345abcdef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '12345abcdef-12345abcdef',
    appId: '1:12345abcdef:ios:12345abcdef',
    messagingSenderId: '12345abcdef',
    projectId: 'todo-app-12345abcdef',
    storageBucket: 'todo-app-12345abcdef.appspot.com',
    iosClientId: '180421582189-abcdefgh.apps.googleusercontent.com',
    iosBundleId: 'vn.devera.toDoApp',
  );
}
